/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = ""
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuYmFuY3Rycm9mYnluZ21vemFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNjc4OTIsImV4cCI6MjA5MDY0Mzg5Mn0.vnXkiGNYFIv54QnNubUoT-fjhJbnwRpY8FAcQVhGNio"